run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
